// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJyvQT-Yr3VKU9rua8z4VST-GYFg___q8',
    appId: '1:368429115976:web:36dadf3c9d4c3a5b6ec67d',
    messagingSenderId: '368429115976',
    projectId: 'cashbox-848c3',
    authDomain: 'cashbox-848c3.firebaseapp.com',
    storageBucket: 'cashbox-848c3.appspot.com',
    measurementId: 'G-MW8WSDN5XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWxrqiHXSfirWxJvOExEqBw7wKcHv-fI',
    appId: '1:368429115976:android:73e57bdd011fff5a6ec67d',
    messagingSenderId: '368429115976',
    projectId: 'cashbox-848c3',
    storageBucket: 'cashbox-848c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTcjwz0SPeob4pGqvc3gAHzrbSTMKHxV4',
    appId: '1:368429115976:ios:3b58326a5cb107bd6ec67d',
    messagingSenderId: '368429115976',
    projectId: 'cashbox-848c3',
    storageBucket: 'cashbox-848c3.appspot.com',
    iosClientId: '368429115976-c3i5hjpor6ler0ofr69v2qv9c86tvjg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkbox1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTcjwz0SPeob4pGqvc3gAHzrbSTMKHxV4',
    appId: '1:368429115976:ios:f01e9e6642fe93fb6ec67d',
    messagingSenderId: '368429115976',
    projectId: 'cashbox-848c3',
    storageBucket: 'cashbox-848c3.appspot.com',
    iosClientId: '368429115976-n62ik6m3d6pfmognhhgpoujctk4ea2ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkbox1.RunnerTests',
  );
}
